### ISSUE TITLE
Missing VTIMEZONE component in ics file

### ISSUE THREAD

**Issue by dogawaf** [spatie/calendar-links#73] opened 2019-09-13 21:49 UTC
Hello

When importing an ics file generated by spatie/calendar-links in Outlook 365, the datetime may be in the wrong timezone.
See this thread for a true life story: https://techcommunity.microsoft.com/t5/Office-365-Calendar/Calendar-incorrectly-reading-ics-file-time-and-timezone-are/m-p/715011/highlight/true#M327

According to the Microsoft tech guy, and after reading the [vcalendar rfc](https://tools.ietf.org/html/rfc5545) , it is clear that if a date is given with a timezone, a VTIMEZONE component must be present in the ics file.

**Comment by dogawaf** [comment] 2019-09-17 09:52
@lptn  I would like to address this issue. Do you confirm it?

There is two ways to fix it:
1. add the needed code for generating VTIMEZONE directly to calendar-links 
2. switch to a third-party lib for generating the vcs, like [sabre/vobject](https://packagist.org/packages/sabre/vobject)

**Comment by lptn** [comment] 2020-07-07 13:51
@dogawaf 
>There is two ways to fix it:

We do care about performance of this package, because it used on view layer and a single page can contain a lot of usages of the `$link->ics()`.  Giving this, we can use both options/ways, but should check a performance degradation if we use external packages like `sabre/vobject`.  This is the only reason why https://github.com/spatie/calendar-links/pull/75 still not reviewed (I planned to do some tests, but it requires some time that I still haven't found :) )

**Comment by skarges3** [comment] 2020-07-09 16:56
@lptn Thanks for reopening this! I'm having a similar issue to this, so I just wanted to bump this.

My issue is specifically happening in relation to Daylight Savings. For many users, the fact that the ics file is not explicitly listing a `STANDARD/DAYLIGHT` definition within the VTIMEZONE.

**Comment by timeshifting** [comment] 2020-07-10 01:08
Likewise, many of our users complain the added event is off by an hour due to the missing VTIMEZONE definition.

**Comment by jeremykenedy** [comment] 2020-07-24 21:32
Same issue.

**Comment by dogawaf** [comment] 2020-07-25 20:07
Hi @lptn 
I use "my" PR on production since I pushed it and I did not notice any performance issue, but I do not generate thousands of links at a time.
IMHO I think accuracy is better than performance and #75 should be merged. Then if someone raises a performance issue, it could be addressed later.

**Comment by Sediug** [comment] 2020-08-04 18:28
> Hi @lptn
> I use "my" PR on production since I pushed it and I did not notice any performance issue, but I do not generate thousands of links at a time.
> IMHO I think accuracy is better than performance and #75 should be merged. Then if someone raises a performance issue, it could be addressed later.

Same issue here, I agree with @dogawaf accuracy > performance.

**Comment by jeremykenedy** [comment] 2020-08-04 18:48
I was able to work around this issue but sending the timezone that I have stored in the database and send the converted (done in the model) time already. 

```php
$timezone = $user && $user->timezone ? $user->timezone : config('app.timezone');

if ($user) {
    $from = DateTime::createFromFormat('Y-m-d H:i:s', $item->startTimeLocal()->format('Y-m-d H:i:s'), new DateTimeZone($timezone));
    $to = $item->item_end_at ? DateTime::createFromFormat('Y-m-d H:i:s', $item->endTimeLocal()->format('Y-m-d H:i:s'), new DateTimeZone($timezone)) : $from;
} else {
    $from = DateTime::createFromFormat('Y-m-d H:i:s', $item->startTimeLocal()->format('Y-m-d H:i:s'));
    $to = $item->item_end_at ? DateTime::createFromFormat('Y-m-d H:i:s', $item->endTimeLocal()->format('Y-m-d H:i:s')) : $from;
}

$link = Link::create($item->name, $from, $to)
    ->description($item->description);


$link->google()
$link->yahoo()
$link->webOutlook()
$link->ics()
```


Item Model:
```php
use Carbon\Carbon;
use JamesMills\LaravelTimezone\Facades\Timezone;

...

/**
 * Convert the start time display from UTC to the USERS local timezone
 * Only works for logged in users. for public areas send in UTC ansd use moment.js to convert.
 */
public function startTimeLocal()
{
    return Carbon::parse(Timezone::convertToLocal($this->item_start_at));
}
```

**Comment by cdubz** [comment] 2020-08-08 18:17
I'm sure there is a better to do this but as @lptn hasn't had the chance to test, I tried a benchmark comparison using the [phpbench](https://phpbench.readthedocs.io/) library with this benchmark:

```
<?php

use Spatie\CalendarLinks\Link;

class LinkBench
{
    public function provideDates()
    {
        return [
            [ 'from' => '2020-01-01 09:00', 'to' => '2020-01-01 18:00' ],
            [ 'from' => '2020-02-01 09:00', 'to' => '2020-02-02 09:00' ],
            [ 'from' => '2020-03-01 09:00', 'to' => '2020-03-07 07:00' ],
            [ 'from' => '2020-04-01 23:00', 'to' => '2020-04-02 01:00' ],
            [ 'from' => '2020-05-15 09:00', 'to' => '2020-05-15 18:00' ],
            [ 'from' => '2020-06-24 09:00', 'to' => '2020-06-28 18:00' ],
            [ 'from' => '2020-07-30 09:00', 'to' => '2020-08-21 18:00' ],
            [ 'from' => '2020-08-01 09:00', 'to' => '2020-08-05 18:00' ],
            [ 'from' => '2020-09-02 12:00', 'to' => '2020-09-02 12:30' ],
            [ 'from' => '2020-10-10 10:10', 'to' => '2020-11-11 11:11' ],
            [ 'from' => '2020-11-02 09:00', 'to' => '2020-11-03 18:00' ],
            [ 'from' => '2020-12-01 01:00', 'to' => '2020-12-31 23:00' ],
        ];
    }

    /**
     * @Revs(1000)
     * @Iterations(100)
     * @ParamProviders({"provideDates"})
     */
    public function benchLink($params)
    {
        Link::create(
            'Benchmark',
            DateTime::createFromFormat('Y-m-d H:i', $params['from']),
            DateTime::createFromFormat('Y-m-d H:i', $params['to'])
        )->ics();
    }
}
```

and ran it on both the current `master` and `dogawaf/calendar-links:issue-73`:

```
[checkout spatie/calendar-links:master]
./vendor/bin/phpbench run benchmarks/LinkBench.php --tag=spatie --store
[checkout dogawaf/calendar-links:issue-73]
./vendor/bin/phpbench run benchmarks/LinkBench.php --tag=dogawaf --store
vendor/bin/phpbench report --uuid=tag:spatie --uuid=tag:dogawaf --report='{extends: compare, compare: tag}'
+-----------+-----------+-----+------+-----------------+------------------+
| benchmark | subject   | set | revs | tag:spatie:mean | tag:dogawaf:mean |
+-----------+-----------+-----+------+-----------------+------------------+
| LinkBench | benchLink | 0   | 1000 | 34.537μs        | 706.495μs        |
| LinkBench | benchLink | 1   | 1000 | 34.366μs        | 706.387μs        |
| LinkBench | benchLink | 2   | 1000 | 34.311μs        | 707.796μs        |
| LinkBench | benchLink | 3   | 1000 | 34.393μs        | 705.612μs        |
| LinkBench | benchLink | 4   | 1000 | 34.425μs        | 706.226μs        |
| LinkBench | benchLink | 5   | 1000 | 34.322μs        | 707.607μs        |
| LinkBench | benchLink | 6   | 1000 | 34.857μs        | 710.536μs        |
| LinkBench | benchLink | 7   | 1000 | 34.403μs        | 705.023μs        |
| LinkBench | benchLink | 8   | 1000 | 34.453μs        | 708.100μs        |
| LinkBench | benchLink | 9   | 1000 | 34.395μs        | 804.409μs        |
| LinkBench | benchLink | 10  | 1000 | 34.327μs        | 706.049μs        |
| LinkBench | benchLink | 11  | 1000 | 34.426μs        | 708.104μs        |
+-----------+-----------+-----+------+-----------------+------------------+
```

That does seem like a considerable performance difference, though we are talking about microsecond differences here, and I'm sure there are better ways to benchmark.

**Comment by ednailor** [comment] 2020-08-26 16:22
This issue is still present. Without the VTIMEZONE information, Outlook does not recognize daylight savings time at all.

The format I have added is as follows:

BEGIN:VTIMEZONE
TZID:America/New_York
X-LIC-LOCATION:America/New_York
BEGIN:DAYLIGHT
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
TZNAME:EDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
TZNAME:EST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE


Of course, there should be something that helps determine the timezone and offsets. As my application only needs America/New_York, I have not taken the additional time to sort that out.

**Comment by lptn** [comment] 2020-08-27 11:51
Hey
@cdubz
@ednailor
@dogawaf 
@jeremykenedy 

Thanks for all your comments and work!

It seems like I'm the only one active collaborator of this repo. Unfortunately, I don't have enough time to explore the problem. But you can help me :) Let's find together a working minimal set of ICS rules that we can use in this package. Then, we can focus on a solution.

This package should:
 - produce small output (too keep pagesize small)
 - fast (no any external heavy dependencies)
 - features should be supported by at least 2 generators (different services have different features)

Using this values, we can improve this package and keep performance, architecture and quality at the hight level.

I ask you guys to share a minimal set of ICS rules that works in your situation. Also, please share how have you tested your solution.

**Comment by dylanlawrence** [comment] 2020-09-08 18:02
### +1 to merge #75.
IMHO If you are doing this to thousands at a time,  you probably need to rethink your design / cache etc.
The processes behind creating the properly formatted vobject w/VTIMEZONE - if they can even get any quicker,  will probably happen on the sabre/vobject project. In the mean time everyone using outlook will see this failure of an inaccurate date.  
**ACCURACY FIRST!**
Just imagine the CEO of some company booking a flight for the wrong date right now cuz one of our little meeting buttons gave everyone the right date except them.

**Comment by reggieofarrell** [comment] 2020-09-09 19:51
Another +1 on merging #75 here.  For the moment I've forked the repo and integrated the @dogawaf changes to ensure accuracy.  I also am only generating a few calendar links at a time.  Accuracy is definitely top priority.

**Comment by c24o** [comment] 2020-09-11 12:29
I do agree about accuracy is more important than performance and it would be nice to see #75 merged.

In the meanwhile, a turn around that I am using is converting the dates to UTC before creating the ICS link. Then the calendar app handles the timezone conversion.

**Comment by jackbsv** [comment] 2020-10-09 18:50
@dogawaf Thanks for your hard work on this one.

As a quick fix for the channel (while the #75 MR sits in a pending state for eternity), you can load in the relevant branch in your `composer.json` by implementing `"spatie/calendar-links": "dev-issue-73",` in the `require` object.

**Comment by blorange2** [comment] 2020-10-14 14:46
@jackbsv how do you go about pulling in a specific branch as opposed to a version constraint?

**Comment by blorange2** [comment] 2020-10-14 15:13
@jackbsv like so?

```

    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/spatie/calendar-links"
        }
    ],

```

Then, do i need to alias like so?

```

        "spatie/calendar-links": "dev-issue-73 as 1.4.2",

```

However, this still gives the following:

  Problem 1
    - The requested package spatie/calendar-links dev-issue-73 as 1.4.2 exists as spatie/calendar-links[0.0.1, 0.1.0, 0.1.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, dev-master] but these are rejected by your constraint.

**Comment by jackbsv** [comment] 2020-10-14 15:48
@blorange2 I think I originally tried to read my own fork from GitLab and it worked okay. I didn't need to use the `as` flag in the version string but I'm guessing if composer says it's okay, then it's okay?

**Comment by munkiepus** [comment] 2020-10-21 08:29
> I do agree about accuracy is more important than performance and it would be nice to see #75 merged.
> 
> In the meanwhile, a turn around that I am using is converting the dates to UTC before creating the ICS link. Then the calendar app handles the timezone conversion.

how did you do that?

**Closed** 2021-02-22 11:02 UTC
Labels: bug

**Comment by adamfranco** [comment] 2021-05-07 15:52
The auto-closing of this issue is unfortunate. I'm enountering this issue as well and seeing Outlook not respecting daylight savings and shifting events by an hour.

**Comment by lptn** [comment] 2021-05-07 15:57
the issue is still looking for it's hero to implement, even iff it's closed :)

**Comment by cdubz** [comment] 2021-05-08 13:27
@lptn the consensus seems to be for merging #75. Are you rejecting that approach or just waiting for revisions based on your review there?

**Comment by mattpaz** [comment] 2021-05-21 18:00
@cdubz - It, indeed, looks like some changes were requested from a [code review](https://github.com/spatie/calendar-links/pull/75#pullrequestreview-521175330) on PR #75 by @dogawaf that haven't been made yet.  

I'd imagine that might be the blocker.  @lptn, can you confirm and/or provide thoughts on whether or not this might see new life with issue #119 ?

Given the age of the original PR (575 days old), I imagine it might need a fresh set of eyes either way.   Given [recent comments](https://github.com/spatie/calendar-links/issues/73#issuecomment-834566230) from @lptn I imagine that is the case. 

Hopefully @lptn will be able to weigh in provide more insight.

**Comment by wxactly** [comment] 2022-07-29 17:28
I tested #140 with calendar-links version 1.7.2 and I can confirm that it fixes the DST hour-offset bug that we have been seeing in Outlook. Can we revive this issue (and/or #119) and re-open #140?
